sonar.projectKey=bckirkup_Anaglyph
sonar.organization=bckirkup
sonar.sources=main.py,camera_manager.py,calibration.py,gui.py,compositor.py,video_recorder.py,still_capture.py
sonar.tests=tests
sonar.sourceEncoding=UTF-8
